version: "3"
services:
  db:
    hostname: db
    image: mysql:latest
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dostavim

  app:
    container_name: spring-boot-application
    image: spring-boot
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
